#neon-prod
spring.datasource.url=${DB_URL_PROD}
spring.datasource.username=${DE_USERNAME_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}
spring.datasource.hikari.connection-timeout=30000

spring.flyway.enabled=true

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate